module Evergreen.Migrate.V4 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V3.GameObjectIds
import Evergreen.V3.GameObjectTypes
import Evergreen.V3.Types
import Evergreen.V4.GameObjectIds
import Evergreen.V4.GameObjectTypes
import Evergreen.V4.Types
import Lamdera.Migrations exposing (..)
import SeqSet


frontendModel : Evergreen.V3.Types.FrontendModel -> ModelMigration Evergreen.V4.Types.FrontendModel Evergreen.V4.Types.FrontendMsg
frontendModel old =
    ModelUnchanged


backendModel : Evergreen.V3.Types.BackendModel -> ModelMigration Evergreen.V4.Types.BackendModel Evergreen.V4.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V3.Types.FrontendMsg -> MsgMigration Evergreen.V4.Types.FrontendMsg Evergreen.V4.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V3.Types.ToBackend -> MsgMigration Evergreen.V4.Types.ToBackend Evergreen.V4.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V3.Types.BackendMsg -> MsgMigration Evergreen.V4.Types.BackendMsg Evergreen.V4.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V3.Types.ToFrontend -> MsgMigration Evergreen.V4.Types.ToFrontend Evergreen.V4.Types.FrontendMsg
toFrontend old =
    MsgUnchanged


migrate_GameObjectIds_DirtId : Evergreen.V3.GameObjectIds.DirtId -> Evergreen.V4.GameObjectIds.DirtId
migrate_GameObjectIds_DirtId old =
    case old of
        Evergreen.V3.GameObjectIds.DirtId p0 ->
            Evergreen.V4.GameObjectIds.DirtId p0


migrate_GameObjectIds_PersonId : Evergreen.V3.GameObjectIds.PersonId -> Evergreen.V4.GameObjectIds.PersonId
migrate_GameObjectIds_PersonId old =
    case old of
        Evergreen.V3.GameObjectIds.PersonId p0 ->
            Evergreen.V4.GameObjectIds.PersonId p0


migrate_GameObjectIds_RelicId : Evergreen.V3.GameObjectIds.RelicId -> Evergreen.V4.GameObjectIds.RelicId
migrate_GameObjectIds_RelicId old =
    case old of
        Evergreen.V3.GameObjectIds.RelicId p0 ->
            Evergreen.V4.GameObjectIds.RelicId p0


migrate_GameObjectTypes_ActionOnGamestate : Evergreen.V3.GameObjectTypes.ActionOnGamestate -> Evergreen.V4.GameObjectTypes.ActionOnGamestate
migrate_GameObjectTypes_ActionOnGamestate old =
    case old of
        Evergreen.V3.GameObjectTypes.MovePerson p0 p1 ->
            Evergreen.V4.GameObjectTypes.MovePerson (p0 |> migrate_GameObjectIds_PersonId)
                (p1 |> migrate_GameObjectTypes_Direction)

        Evergreen.V3.GameObjectTypes.Clean p0 p1 ->
            Evergreen.V4.GameObjectTypes.Clean (p0 |> migrate_GameObjectIds_PersonId)
                (p1 |> migrate_GameObjectTypes_Point)

        Evergreen.V3.GameObjectTypes.AddDirt p0 ->
            Evergreen.V4.GameObjectTypes.AddDirt (p0 |> migrate_GameObjectTypes_DirtData)

        Evergreen.V3.GameObjectTypes.AddRelic p0 p1 ->
            Evergreen.V4.GameObjectTypes.AddRelic (p0 |> migrate_GameObjectTypes_RelicData)
                (p1 |> migrate_GameObjectTypes_Point)

        Evergreen.V3.GameObjectTypes.AddPerson p0 ->
            Evergreen.V4.GameObjectTypes.AddPerson (p0 |> migrate_GameObjectTypes_PersonData)

        Evergreen.V3.GameObjectTypes.PickUpRelic p0 p1 ->
            Evergreen.V4.GameObjectTypes.PickUpRelic (p0 |> migrate_GameObjectIds_RelicId)
                (p1 |> migrate_GameObjectIds_PersonId)

        Evergreen.V3.GameObjectTypes.DropRelic p0 p1 ->
            Evergreen.V4.GameObjectTypes.DropRelic (p0 |> migrate_GameObjectIds_RelicId)
                (p1 |> migrate_GameObjectIds_PersonId)

        Evergreen.V3.GameObjectTypes.ActivateGenerosityTrap p0 p1 p2 ->
            Evergreen.V4.GameObjectTypes.ActivateGenerosityTrap (p0 |> migrate_GameObjectIds_PersonId)
                (p1 |> migrate_GameObjectIds_RelicId)
                p2

        Evergreen.V3.GameObjectTypes.BatchAction p0 ->
            Evergreen.V4.GameObjectTypes.BatchAction (p0 |> List.map migrate_GameObjectTypes_ActionOnGamestate)

        Evergreen.V3.GameObjectTypes.GameStateNoOp ->
            Evergreen.V4.GameObjectTypes.GameStateNoOp


migrate_GameObjectTypes_Direction : Evergreen.V3.GameObjectTypes.Direction -> Evergreen.V4.GameObjectTypes.Direction
migrate_GameObjectTypes_Direction old =
    case old of
        Evergreen.V3.GameObjectTypes.Up ->
            Evergreen.V4.GameObjectTypes.Up

        Evergreen.V3.GameObjectTypes.Down ->
            Evergreen.V4.GameObjectTypes.Down

        Evergreen.V3.GameObjectTypes.Left ->
            Evergreen.V4.GameObjectTypes.Left

        Evergreen.V3.GameObjectTypes.Right ->
            Evergreen.V4.GameObjectTypes.Right

        Evergreen.V3.GameObjectTypes.UpLeft ->
            Evergreen.V4.GameObjectTypes.UpLeft

        Evergreen.V3.GameObjectTypes.UpRight ->
            Evergreen.V4.GameObjectTypes.UpRight

        Evergreen.V3.GameObjectTypes.DownLeft ->
            Evergreen.V4.GameObjectTypes.DownLeft

        Evergreen.V3.GameObjectTypes.DownRight ->
            Evergreen.V4.GameObjectTypes.DownRight


migrate_GameObjectTypes_DirtData : Evergreen.V3.GameObjectTypes.DirtData -> Evergreen.V4.GameObjectTypes.DirtData
migrate_GameObjectTypes_DirtData old =
    { id = old.id |> migrate_GameObjectIds_DirtId
    , amount = old.amount
    , position = old.position |> migrate_GameObjectTypes_Point
    }


migrate_GameObjectTypes_PersonData : Evergreen.V3.GameObjectTypes.PersonData -> Evergreen.V4.GameObjectTypes.PersonData
migrate_GameObjectTypes_PersonData old =
    { id = old.id |> migrate_GameObjectIds_PersonId
    , name = old.name
    , experience = old.experience
    , position = old.position |> migrate_GameObjectTypes_Point
    , stats = old.stats |> migrate_GameObjectTypes_PersonStats
    }


migrate_GameObjectTypes_PersonStats : Evergreen.V3.GameObjectTypes.PersonStats -> Evergreen.V4.GameObjectTypes.PersonStats
migrate_GameObjectTypes_PersonStats old =
    old


migrate_GameObjectTypes_Point : Evergreen.V3.GameObjectTypes.Point -> Evergreen.V4.GameObjectTypes.Point
migrate_GameObjectTypes_Point old =
    old


migrate_GameObjectTypes_RelicData : Evergreen.V3.GameObjectTypes.RelicData -> Evergreen.V4.GameObjectTypes.RelicData
migrate_GameObjectTypes_RelicData old =
    { id = old.id |> migrate_GameObjectIds_RelicId
    , relicType = old.relicType |> migrate_GameObjectTypes_RelicType
    , rarity = old.rarity |> migrate_GameObjectTypes_RelicRarity
    , exp = old.exp
    }


migrate_GameObjectTypes_RelicRarity : Evergreen.V3.GameObjectTypes.RelicRarity -> Evergreen.V4.GameObjectTypes.RelicRarity
migrate_GameObjectTypes_RelicRarity old =
    case old of
        Evergreen.V3.GameObjectTypes.Common ->
            Evergreen.V4.GameObjectTypes.Common

        Evergreen.V3.GameObjectTypes.Uncommon ->
            Evergreen.V4.GameObjectTypes.Uncommon

        Evergreen.V3.GameObjectTypes.Rare ->
            Evergreen.V4.GameObjectTypes.Rare

        Evergreen.V3.GameObjectTypes.Epic ->
            Evergreen.V4.GameObjectTypes.Epic

        Evergreen.V3.GameObjectTypes.Legendary ->
            Evergreen.V4.GameObjectTypes.Legendary


migrate_GameObjectTypes_RelicType : Evergreen.V3.GameObjectTypes.RelicType -> Evergreen.V4.GameObjectTypes.RelicType
migrate_GameObjectTypes_RelicType old =
    case old of
        Evergreen.V3.GameObjectTypes.CleanFast ->
            Evergreen.V4.GameObjectTypes.CleanFast

        Evergreen.V3.GameObjectTypes.MoreXP ->
            Evergreen.V4.GameObjectTypes.MoreXP

        Evergreen.V3.GameObjectTypes.DropAndDouble p0 ->
            Evergreen.V4.GameObjectTypes.DropAndDouble (p0 |> List.map migrate_GameObjectIds_PersonId)

        Evergreen.V3.GameObjectTypes.SplashBucket ->
            Evergreen.V4.GameObjectTypes.SplashBucket

        Evergreen.V3.GameObjectTypes.GuestBook p0 ->
            Evergreen.V4.GameObjectTypes.GuestBook (p0 |> SeqSet.map migrate_GameObjectIds_PersonId)

        Evergreen.V3.GameObjectTypes.DiminishingPower p0 ->
            Evergreen.V4.GameObjectTypes.DiminishingPower p0


migrate_Types_FrontendMsg : Evergreen.V3.Types.FrontendMsg -> Evergreen.V4.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V3.Types.UrlClicked p0 ->
            Evergreen.V4.Types.UrlClicked p0

        Evergreen.V3.Types.UrlChanged p0 ->
            Evergreen.V4.Types.UrlChanged p0

        Evergreen.V3.Types.PerformAction p0 ->
            Evergreen.V4.Types.PerformAction (p0 |> migrate_GameObjectTypes_ActionOnGamestate)

        Evergreen.V3.Types.ClickedPleaseMakeMeDirty ->
            Evergreen.V4.Types.ClickedPleaseMakeMeDirty

        Evergreen.V3.Types.DebugGenerateRelic ->
            Evergreen.V4.Types.DebugGenerateRelic

        Evergreen.V3.Types.ActivatedRelic p0 p1 ->
            Evergreen.V4.Types.ActivatedRelic (p0 |> migrate_GameObjectIds_PersonId)
                (p1 |> migrate_GameObjectIds_RelicId)

        Evergreen.V3.Types.ClickTarget p0 ->
            Evergreen.V4.Types.ClickTarget (p0 |> migrate_GameObjectTypes_Point)

        Evergreen.V3.Types.Tick p0 ->
            Evergreen.V4.Types.Tick p0

        Evergreen.V3.Types.ToggleDebugStuff ->
            Evergreen.V4.Types.ToggleDebugStuff

        Evergreen.V3.Types.CloseModals ->
            Evergreen.V4.Types.CloseModals

        Evergreen.V3.Types.ReceivedMapSize p0 ->
            Evergreen.V4.Types.ReceivedMapSize p0

        Evergreen.V3.Types.ToggleMobileRelicMenu ->
            Evergreen.V4.Types.ToggleMobileRelicMenu

        Evergreen.V3.Types.NoOpFrontendMsg ->
            Evergreen.V4.Types.NoOpFrontendMsg


migrate_Types_ToBackend : Evergreen.V3.Types.ToBackend -> Evergreen.V4.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V3.Types.NoOpToBackend ->
            Evergreen.V4.Types.NoOpToBackend

        Evergreen.V3.Types.ClientPerformsAction p0 ->
            Evergreen.V4.Types.ClientPerformsAction (p0 |> migrate_GameObjectTypes_ActionOnGamestate)

        Evergreen.V3.Types.PleaseMakeMeDirty ->
            Evergreen.V4.Types.PleaseMakeMeDirty

        Evergreen.V3.Types.PleaseGenerateRelic ->
            Evergreen.V4.Types.PleaseGenerateRelic

        Evergreen.V3.Types.PleaseActivateRelic p0 p1 ->
            Evergreen.V4.Types.PleaseActivateRelic (p0 |> migrate_GameObjectIds_PersonId)
                (p1 |> migrate_GameObjectIds_RelicId)
