module Evergreen.Migrate.V4 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Evergreen.V2.GameObjectIds
import Evergreen.V2.GameObjectTypes
import Evergreen.V2.Types
import Evergreen.V4.GameObjectIds
import Evergreen.V4.GameObjectTypes
import Evergreen.V4.Types
import Lamdera.Migrations exposing (..)
import List
import Maybe
import SeqDict
import SeqSet


frontendModel : Evergreen.V2.Types.FrontendModel -> ModelMigration Evergreen.V4.Types.FrontendModel Evergreen.V4.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V2.Types.BackendModel -> ModelMigration Evergreen.V4.Types.BackendModel Evergreen.V4.Types.BackendMsg
backendModel old =
    ModelUnchanged


frontendMsg : Evergreen.V2.Types.FrontendMsg -> MsgMigration Evergreen.V4.Types.FrontendMsg Evergreen.V4.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V2.Types.ToBackend -> MsgMigration Evergreen.V4.Types.ToBackend Evergreen.V4.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V2.Types.BackendMsg -> MsgMigration Evergreen.V4.Types.BackendMsg Evergreen.V4.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V2.Types.ToFrontend -> MsgMigration Evergreen.V4.Types.ToFrontend Evergreen.V4.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_FrontendModel : Evergreen.V2.Types.FrontendModel -> Evergreen.V4.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , state = old.state |> migrate_Types_FrontendState
    }


migrate_GameObjectIds_DirtId : Evergreen.V2.GameObjectIds.DirtId -> Evergreen.V4.GameObjectIds.DirtId
migrate_GameObjectIds_DirtId old =
    case old of
        Evergreen.V2.GameObjectIds.DirtId p0 ->
            Evergreen.V4.GameObjectIds.DirtId p0


migrate_GameObjectIds_PersonId : Evergreen.V2.GameObjectIds.PersonId -> Evergreen.V4.GameObjectIds.PersonId
migrate_GameObjectIds_PersonId old =
    case old of
        Evergreen.V2.GameObjectIds.PersonId p0 ->
            Evergreen.V4.GameObjectIds.PersonId p0


migrate_GameObjectIds_RelicId : Evergreen.V2.GameObjectIds.RelicId -> Evergreen.V4.GameObjectIds.RelicId
migrate_GameObjectIds_RelicId old =
    case old of
        Evergreen.V2.GameObjectIds.RelicId p0 ->
            Evergreen.V4.GameObjectIds.RelicId p0


migrate_GameObjectTypes_ActionId : Evergreen.V2.GameObjectTypes.ActionId -> Evergreen.V4.GameObjectTypes.ActionId
migrate_GameObjectTypes_ActionId old =
    case old of
        Evergreen.V2.GameObjectTypes.ActionId p0 ->
            Evergreen.V4.GameObjectTypes.ActionId p0


migrate_GameObjectTypes_ActionOnGamestate : Evergreen.V2.GameObjectTypes.ActionOnGamestate -> Evergreen.V4.GameObjectTypes.ActionOnGamestate
migrate_GameObjectTypes_ActionOnGamestate old =
    case old of
        Evergreen.V2.GameObjectTypes.MovePerson p0 p1 ->
            Evergreen.V4.GameObjectTypes.MovePerson (p0 |> migrate_GameObjectIds_PersonId)
                (p1 |> migrate_GameObjectTypes_Direction)

        Evergreen.V2.GameObjectTypes.Clean p0 p1 ->
            Evergreen.V4.GameObjectTypes.Clean (p0 |> migrate_GameObjectIds_PersonId)
                (p1 |> migrate_GameObjectTypes_Point)

        Evergreen.V2.GameObjectTypes.AddDirt p0 ->
            Evergreen.V4.GameObjectTypes.AddDirt (p0 |> migrate_GameObjectTypes_DirtData)

        Evergreen.V2.GameObjectTypes.AddRelic p0 p1 ->
            Evergreen.V4.GameObjectTypes.AddRelic (p0 |> migrate_GameObjectTypes_RelicData)
                (p1 |> migrate_GameObjectTypes_Point)

        Evergreen.V2.GameObjectTypes.AddPerson p0 ->
            Evergreen.V4.GameObjectTypes.AddPerson (p0 |> migrate_GameObjectTypes_PersonData)

        Evergreen.V2.GameObjectTypes.PickUpRelic p0 p1 ->
            Evergreen.V4.GameObjectTypes.PickUpRelic (p0 |> migrate_GameObjectIds_RelicId)
                (p1 |> migrate_GameObjectIds_PersonId)

        Evergreen.V2.GameObjectTypes.DropRelic p0 p1 ->
            Evergreen.V4.GameObjectTypes.DropRelic (p0 |> migrate_GameObjectIds_RelicId)
                (p1 |> migrate_GameObjectIds_PersonId)

        Evergreen.V2.GameObjectTypes.ActivateGenerosityTrap p0 p1 ->
            Evergreen.V4.GameObjectTypes.ActivateGenerosityTrap (p0 |> migrate_GameObjectIds_PersonId)
                (p1 |> migrate_GameObjectIds_RelicId)

        Evergreen.V2.GameObjectTypes.UnlockSkillAction p0 p1 ->
            Evergreen.V4.GameObjectTypes.UnlockSkillAction (p0 |> migrate_GameObjectIds_PersonId)
                (p1 |> migrate_GameObjectTypes_Skill)

        Evergreen.V2.GameObjectTypes.BatchAction p0 ->
            Evergreen.V4.GameObjectTypes.BatchAction (p0 |> List.map migrate_GameObjectTypes_ActionOnGamestate)

        Evergreen.V2.GameObjectTypes.GameStateNoOp ->
            Evergreen.V4.GameObjectTypes.GameStateNoOp


migrate_GameObjectTypes_ActionWithMetadata : Evergreen.V2.GameObjectTypes.ActionWithMetadata -> Evergreen.V4.GameObjectTypes.ActionWithMetadata
migrate_GameObjectTypes_ActionWithMetadata old =
    { action = old.action |> migrate_GameObjectTypes_ActionOnGamestate
    , performer = old.performer |> migrate_GameObjectIds_PersonId
    , id = old.id |> migrate_GameObjectTypes_ActionId
    }


migrate_GameObjectTypes_Direction : Evergreen.V2.GameObjectTypes.Direction -> Evergreen.V4.GameObjectTypes.Direction
migrate_GameObjectTypes_Direction old =
    case old of
        Evergreen.V2.GameObjectTypes.Up ->
            Evergreen.V4.GameObjectTypes.Up

        Evergreen.V2.GameObjectTypes.Down ->
            Evergreen.V4.GameObjectTypes.Down

        Evergreen.V2.GameObjectTypes.Left ->
            Evergreen.V4.GameObjectTypes.Left

        Evergreen.V2.GameObjectTypes.Right ->
            Evergreen.V4.GameObjectTypes.Right

        Evergreen.V2.GameObjectTypes.UpLeft ->
            Evergreen.V4.GameObjectTypes.UpLeft

        Evergreen.V2.GameObjectTypes.UpRight ->
            Evergreen.V4.GameObjectTypes.UpRight

        Evergreen.V2.GameObjectTypes.DownLeft ->
            Evergreen.V4.GameObjectTypes.DownLeft

        Evergreen.V2.GameObjectTypes.DownRight ->
            Evergreen.V4.GameObjectTypes.DownRight


migrate_GameObjectTypes_DirtData : Evergreen.V2.GameObjectTypes.DirtData -> Evergreen.V4.GameObjectTypes.DirtData
migrate_GameObjectTypes_DirtData old =
    { id = old.id |> migrate_GameObjectIds_DirtId
    , amount = old.amount
    , maxAmount = old.maxAmount
    , position = old.position |> migrate_GameObjectTypes_Point
    }


migrate_GameObjectTypes_HighFiveBoost : Evergreen.V2.GameObjectTypes.HighFiveBoost -> Evergreen.V4.GameObjectTypes.HighFiveBoost
migrate_GameObjectTypes_HighFiveBoost old =
    { boost = old.boost
    , giver = old.giver |> migrate_GameObjectIds_PersonId
    }


migrate_GameObjectTypes_PersonData : Evergreen.V2.GameObjectTypes.PersonData -> Evergreen.V4.GameObjectTypes.PersonData
migrate_GameObjectTypes_PersonData old =
    { id = old.id |> migrate_GameObjectIds_PersonId
    , name = old.name
    , experience = old.experience
    , position = old.position |> migrate_GameObjectTypes_Point
    , stats = old.stats |> migrate_GameObjectTypes_PersonStats
    , bestHighFiveBoost = old.bestHighFiveBoost |> Maybe.map migrate_GameObjectTypes_HighFiveBoost
    , skillTree = old.skillTree |> migrate_GameObjectTypes_SkillTree
    }


migrate_GameObjectTypes_PersonStats : Evergreen.V2.GameObjectTypes.PersonStats -> Evergreen.V4.GameObjectTypes.PersonStats
migrate_GameObjectTypes_PersonStats old =
    old


migrate_GameObjectTypes_Point : Evergreen.V2.GameObjectTypes.Point -> Evergreen.V4.GameObjectTypes.Point
migrate_GameObjectTypes_Point old =
    old


migrate_GameObjectTypes_RelicData : Evergreen.V2.GameObjectTypes.RelicData -> Evergreen.V4.GameObjectTypes.RelicData
migrate_GameObjectTypes_RelicData old =
    { id = old.id |> migrate_GameObjectIds_RelicId
    , relicType = old.relicType |> migrate_GameObjectTypes_RelicType
    , rarity = old.rarity |> migrate_GameObjectTypes_RelicRarity
    , exp = old.exp
    }


migrate_GameObjectTypes_RelicPosition : Evergreen.V2.GameObjectTypes.RelicPosition -> Evergreen.V4.GameObjectTypes.RelicPosition
migrate_GameObjectTypes_RelicPosition old =
    case old of
        Evergreen.V2.GameObjectTypes.HeldBy p0 ->
            Evergreen.V4.GameObjectTypes.HeldBy (p0 |> migrate_GameObjectIds_PersonId)

        Evergreen.V2.GameObjectTypes.OnFloor p0 ->
            Evergreen.V4.GameObjectTypes.OnFloor (p0 |> migrate_GameObjectTypes_Point)


migrate_GameObjectTypes_RelicRarity : Evergreen.V2.GameObjectTypes.RelicRarity -> Evergreen.V4.GameObjectTypes.RelicRarity
migrate_GameObjectTypes_RelicRarity old =
    case old of
        Evergreen.V2.GameObjectTypes.Common ->
            Evergreen.V4.GameObjectTypes.Common

        Evergreen.V2.GameObjectTypes.Uncommon ->
            Evergreen.V4.GameObjectTypes.Uncommon

        Evergreen.V2.GameObjectTypes.Rare ->
            Evergreen.V4.GameObjectTypes.Rare

        Evergreen.V2.GameObjectTypes.Epic ->
            Evergreen.V4.GameObjectTypes.Epic

        Evergreen.V2.GameObjectTypes.Legendary ->
            Evergreen.V4.GameObjectTypes.Legendary


migrate_GameObjectTypes_RelicType : Evergreen.V2.GameObjectTypes.RelicType -> Evergreen.V4.GameObjectTypes.RelicType
migrate_GameObjectTypes_RelicType old =
    case old of
        Evergreen.V2.GameObjectTypes.Broom ->
            Evergreen.V4.GameObjectTypes.Broom

        Evergreen.V2.GameObjectTypes.Mop ->
            Evergreen.V4.GameObjectTypes.Mop

        Evergreen.V2.GameObjectTypes.MoreXP ->
            Evergreen.V4.GameObjectTypes.MoreXP

        Evergreen.V2.GameObjectTypes.DropAndDouble p0 ->
            Evergreen.V4.GameObjectTypes.DropAndDouble (p0 |> List.map migrate_GameObjectIds_PersonId)

        Evergreen.V2.GameObjectTypes.SplashBucket ->
            Evergreen.V4.GameObjectTypes.SplashBucket

        Evergreen.V2.GameObjectTypes.GuestBook p0 ->
            Evergreen.V4.GameObjectTypes.GuestBook (p0 |> SeqSet.map migrate_GameObjectIds_PersonId)

        Evergreen.V2.GameObjectTypes.DiminishingPower p0 ->
            Evergreen.V4.GameObjectTypes.DiminishingPower p0

        Evergreen.V2.GameObjectTypes.HighFive ->
            Evergreen.V4.GameObjectTypes.HighFive

        Evergreen.V2.GameObjectTypes.MetalDetector ->
            Evergreen.V4.GameObjectTypes.MetalDetector


migrate_GameObjectTypes_Skill : Evergreen.V2.GameObjectTypes.Skill -> Evergreen.V4.GameObjectTypes.Skill
migrate_GameObjectTypes_Skill old =
    case old of
        Evergreen.V2.GameObjectTypes.Root ->
            Evergreen.V4.GameObjectTypes.Root

        Evergreen.V2.GameObjectTypes.Learned ->
            Evergreen.V4.GameObjectTypes.Learned

        Evergreen.V2.GameObjectTypes.SwiftCleaning ->
            Evergreen.V4.GameObjectTypes.SwiftCleaning

        Evergreen.V2.GameObjectTypes.CleaningFundamentals ->
            Evergreen.V4.GameObjectTypes.CleaningFundamentals

        Evergreen.V2.GameObjectTypes.RelicHunter ->
            Evergreen.V4.GameObjectTypes.RelicHunter

        Evergreen.V2.GameObjectTypes.PowerCleaning ->
            Evergreen.V4.GameObjectTypes.PowerCleaning


migrate_GameObjectTypes_SkillTree : Evergreen.V2.GameObjectTypes.SkillTree -> Evergreen.V4.GameObjectTypes.SkillTree
migrate_GameObjectTypes_SkillTree old =
    old


migrate_Types_ActionPerformer : Evergreen.V2.Types.ActionPerformer -> Evergreen.V4.Types.ActionPerformer
migrate_Types_ActionPerformer old =
    case old of
        Evergreen.V2.Types.Client p0 ->
            Evergreen.V4.Types.Client (p0 |> migrate_GameObjectIds_PersonId)

        Evergreen.V2.Types.Server ->
            Evergreen.V4.Types.Server


migrate_Types_BackendToFrontendState : Evergreen.V2.Types.BackendToFrontendState -> Evergreen.V4.Types.BackendToFrontendState
migrate_Types_BackendToFrontendState old =
    { gameState = old.gameState |> migrate_Types_GameState
    , myId = old.myId |> migrate_GameObjectIds_PersonId
    , debugDirtParams =
        old.debugDirtParams
            |> (\rec -> rec)
    }


migrate_Types_DirtByLocation : Evergreen.V2.Types.DirtByLocation -> Evergreen.V4.Types.DirtByLocation
migrate_Types_DirtByLocation old =
    old |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_GameObjectTypes_Point migrate_GameObjectTypes_DirtData) |> SeqDict.fromList


migrate_Types_FrontendMsg : Evergreen.V2.Types.FrontendMsg -> Evergreen.V4.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V2.Types.UrlClicked p0 ->
            Evergreen.V4.Types.UrlClicked p0

        Evergreen.V2.Types.UrlChanged p0 ->
            Evergreen.V4.Types.UrlChanged p0

        Evergreen.V2.Types.PerformAction p0 ->
            Evergreen.V4.Types.PerformAction (p0 |> migrate_GameObjectTypes_ActionOnGamestate)

        Evergreen.V2.Types.StunSelf ->
            Evergreen.V4.Types.StunSelf

        Evergreen.V2.Types.ClickedPleaseMakeMeDirty ->
            Evergreen.V4.Types.ClickedPleaseMakeMeDirty

        Evergreen.V2.Types.DebugGenerateRelic ->
            Evergreen.V4.Types.DebugGenerateRelic

        Evergreen.V2.Types.ClickTarget p0 ->
            Evergreen.V4.Types.ClickTarget (p0 |> migrate_GameObjectTypes_Point)

        Evergreen.V2.Types.Tick p0 ->
            Evergreen.V4.Types.Tick p0

        Evergreen.V2.Types.AnimationTick p0 ->
            Evergreen.V4.Types.AnimationTick p0

        Evergreen.V2.Types.ToggleDebugStuff ->
            Evergreen.V4.Types.ToggleDebugStuff

        Evergreen.V2.Types.CloseModals ->
            Evergreen.V4.Types.CloseModals

        Evergreen.V2.Types.ReceivedMapSize p0 ->
            Evergreen.V4.Types.ReceivedMapSize p0

        Evergreen.V2.Types.ToggleMobileRelicMenu ->
            Evergreen.V4.Types.ToggleMobileRelicMenu

        Evergreen.V2.Types.ToggleSkillTreeMenu ->
            Evergreen.V4.Types.ToggleSkillTreeMenu

        Evergreen.V2.Types.ClickedSkillNode p0 ->
            Evergreen.V4.Types.ClickedSkillNode (p0 |> migrate_GameObjectTypes_Skill)

        Evergreen.V2.Types.CloseSkillTreeModal ->
            Evergreen.V4.Types.CloseSkillTreeModal

        Evergreen.V2.Types.UnlockSkill p0 ->
            Evergreen.V4.Types.UnlockSkill (p0 |> migrate_GameObjectTypes_Skill)

        Evergreen.V2.Types.NoOpFrontendMsg ->
            Evergreen.V4.Types.NoOpFrontendMsg

        Evergreen.V2.Types.NukeBackend ->
            Evergreen.V4.Types.NukeBackend

        Evergreen.V2.Types.UpdateDebugDirtParamsMsg p0 ->
            Evergreen.V4.Types.UpdateDebugDirtParamsMsg p0


migrate_Types_FrontendPlayingState : Evergreen.V2.Types.FrontendPlayingState -> Evergreen.V4.Types.FrontendPlayingState
migrate_Types_FrontendPlayingState old =
    { backendConfirmedGameState = old.backendConfirmedGameState |> migrate_Types_GameState
    , optimisticActions = old.optimisticActions |> List.map migrate_GameObjectTypes_ActionWithMetadata
    , myId = old.myId |> migrate_GameObjectIds_PersonId
    , targetPosition = old.targetPosition
    , showingDebugStuff = old.showingDebugStuff
    , mapSize = old.mapSize
    , cameraPosition = old.cameraPosition |> migrate_GameObjectTypes_Point
    , mobileRelicMenuOpen = old.mobileRelicMenuOpen
    , skillTreeModalState = old.skillTreeModalState |> migrate_Types_SkillTreeModalState
    , debugDirtParams =
        old.debugDirtParams
            |> (\rec -> rec)
    , currentTime = old.currentTime
    , stunnedUntil = old.stunnedUntil
    , cleaningRandom = old.cleaningRandom
    , nextActionId = old.nextActionId
    }


migrate_Types_FrontendState : Evergreen.V2.Types.FrontendState -> Evergreen.V4.Types.FrontendState
migrate_Types_FrontendState old =
    case old of
        Evergreen.V2.Types.Loading ->
            Evergreen.V4.Types.Loading

        Evergreen.V2.Types.Playing p0 ->
            Evergreen.V4.Types.Playing (p0 |> migrate_Types_FrontendPlayingState)

        Evergreen.V2.Types.Error p0 ->
            Evergreen.V4.Types.Error p0


migrate_Types_GameState : Evergreen.V2.Types.GameState -> Evergreen.V4.Types.GameState
migrate_Types_GameState old =
    { personDict = old.personDict |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_GameObjectIds_PersonId migrate_GameObjectTypes_PersonData) |> SeqDict.fromList
    , relicsByLocation = old.relicsByLocation |> migrate_Types_RelicsByLocation
    , dirtByLocation = old.dirtByLocation |> migrate_Types_DirtByLocation
    , relicIdToLocationIndex = old.relicIdToLocationIndex |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_GameObjectIds_RelicId migrate_GameObjectTypes_RelicPosition) |> SeqDict.fromList
    }


migrate_Types_RelicsById : Evergreen.V2.Types.RelicsById -> Evergreen.V4.Types.RelicsById
migrate_Types_RelicsById old =
    old |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_GameObjectIds_RelicId migrate_GameObjectTypes_RelicData) |> SeqDict.fromList


migrate_Types_RelicsByLocation : Evergreen.V2.Types.RelicsByLocation -> Evergreen.V4.Types.RelicsByLocation
migrate_Types_RelicsByLocation old =
    old |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_GameObjectTypes_RelicPosition migrate_Types_RelicsById) |> SeqDict.fromList


migrate_Types_SkillTreeModalState : Evergreen.V2.Types.SkillTreeModalState -> Evergreen.V4.Types.SkillTreeModalState
migrate_Types_SkillTreeModalState old =
    case old of
        Evergreen.V2.Types.Closed ->
            Evergreen.V4.Types.Closed

        Evergreen.V2.Types.SkillTreeOpen ->
            Evergreen.V4.Types.SkillTreeOpen

        Evergreen.V2.Types.SkillDetailOpen p0 ->
            Evergreen.V4.Types.SkillDetailOpen (p0 |> migrate_GameObjectTypes_Skill)


migrate_Types_ToBackend : Evergreen.V2.Types.ToBackend -> Evergreen.V4.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V2.Types.NoOpToBackend ->
            Evergreen.V4.Types.NoOpToBackend

        Evergreen.V2.Types.ClientPerformsAction p0 ->
            Evergreen.V4.Types.ClientPerformsAction (p0 |> migrate_GameObjectTypes_ActionWithMetadata)

        Evergreen.V2.Types.PleaseMakeMeDirty ->
            Evergreen.V4.Types.PleaseMakeMeDirty

        Evergreen.V2.Types.PleaseGenerateRelic ->
            Evergreen.V4.Types.PleaseGenerateRelic

        Evergreen.V2.Types.PleaseNukeBackend ->
            Evergreen.V4.Types.PleaseNukeBackend

        Evergreen.V2.Types.UpdateDebugDirtParams p0 ->
            Evergreen.V4.Types.UpdateDebugDirtParams p0


migrate_Types_ToFrontend : Evergreen.V2.Types.ToFrontend -> Evergreen.V4.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V2.Types.NoOpToFrontend ->
            Evergreen.V4.Types.NoOpToFrontend

        Evergreen.V2.Types.ServerAction p0 p1 ->
            Evergreen.V4.Types.ServerAction (p0 |> migrate_Types_ActionPerformer)
                (p1 |> migrate_GameObjectTypes_ActionOnGamestate)

        Evergreen.V2.Types.ActionConfirmed p0 ->
            Evergreen.V4.Types.ActionConfirmed (p0 |> migrate_GameObjectTypes_ActionWithMetadata)

        Evergreen.V2.Types.UpdateFullState p0 ->
            Evergreen.V4.Types.UpdateFullState (p0 |> migrate_Types_BackendToFrontendState)
