module Evergreen.Migrate.V6 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Effect.Time
import Evergreen.V4.GameObjectIds
import Evergreen.V4.GameObjectTypes
import Evergreen.V4.Types
import Evergreen.V6.GameObjectIds
import Evergreen.V6.GameObjectTypes
import Evergreen.V6.GameState
import Evergreen.V6.Types
import Lamdera.Migrations exposing (..)
import List
import SeqDict
import SeqSet


frontendModel : Evergreen.V4.Types.FrontendModel -> ModelMigration Evergreen.V6.Types.FrontendModel Evergreen.V6.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V4.Types.BackendModel -> ModelMigration Evergreen.V6.Types.BackendModel Evergreen.V6.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V4.Types.FrontendMsg -> MsgMigration Evergreen.V6.Types.FrontendMsg Evergreen.V6.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V4.Types.ToBackend -> MsgMigration Evergreen.V6.Types.ToBackend Evergreen.V6.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V4.Types.BackendMsg -> MsgMigration Evergreen.V6.Types.BackendMsg Evergreen.V6.Types.BackendMsg
backendMsg old =
    MsgUnchanged


toFrontend : Evergreen.V4.Types.ToFrontend -> MsgMigration Evergreen.V6.Types.ToFrontend Evergreen.V6.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V4.Types.BackendModel -> Evergreen.V6.Types.BackendModel
migrate_Types_BackendModel old =
    { gameState = old.gameState |> migrate_Types_GameState
    , connectedClients = old.connectedClients
    , sessionIdToPersonId = old.sessionIdToPersonId |> SeqDict.map (\k -> migrate_GameObjectIds_PersonId)
    , biggestId = old.biggestId
    , bigRandom = old.bigRandom
    , debugDirtParams = { minX = 0, maxX = 0, minY = 0, maxY = 0 }
    }


migrate_Types_FrontendModel : Evergreen.V4.Types.FrontendModel -> Evergreen.V6.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , state = old.state |> migrate_Types_FrontendState
    }


migrate_GameObjectIds_DirtId : Evergreen.V4.GameObjectIds.DirtId -> Evergreen.V6.GameObjectIds.DirtId
migrate_GameObjectIds_DirtId old =
    case old of
        Evergreen.V4.GameObjectIds.DirtId p0 ->
            Evergreen.V6.GameObjectIds.DirtId p0


migrate_GameObjectIds_PersonId : Evergreen.V4.GameObjectIds.PersonId -> Evergreen.V6.GameObjectIds.PersonId
migrate_GameObjectIds_PersonId old =
    case old of
        Evergreen.V4.GameObjectIds.PersonId p0 ->
            Evergreen.V6.GameObjectIds.PersonId p0


migrate_GameObjectIds_RelicId : Evergreen.V4.GameObjectIds.RelicId -> Evergreen.V6.GameObjectIds.RelicId
migrate_GameObjectIds_RelicId old =
    case old of
        Evergreen.V4.GameObjectIds.RelicId p0 ->
            Evergreen.V6.GameObjectIds.RelicId p0


migrate_GameObjectTypes_ActionOnGamestate : Evergreen.V4.GameObjectTypes.ActionOnGamestate -> Evergreen.V6.GameObjectTypes.ActionOnGamestate
migrate_GameObjectTypes_ActionOnGamestate old =
    case old of
        Evergreen.V4.GameObjectTypes.MovePerson p0 p1 ->
            Evergreen.V6.GameObjectTypes.MovePerson (p0 |> migrate_GameObjectIds_PersonId)
                (p1 |> migrate_GameObjectTypes_Direction)

        Evergreen.V4.GameObjectTypes.Clean p0 p1 ->
            Evergreen.V6.GameObjectTypes.Clean (p0 |> migrate_GameObjectIds_PersonId)
                (p1 |> migrate_GameObjectTypes_Point)

        Evergreen.V4.GameObjectTypes.AddDirt p0 ->
            Evergreen.V6.GameObjectTypes.AddDirt (p0 |> migrate_GameObjectTypes_DirtData)

        Evergreen.V4.GameObjectTypes.AddRelic p0 p1 ->
            Evergreen.V6.GameObjectTypes.AddRelic (p0 |> migrate_GameObjectTypes_RelicData)
                (p1 |> migrate_GameObjectTypes_Point)

        Evergreen.V4.GameObjectTypes.AddPerson p0 ->
            Evergreen.V6.GameObjectTypes.AddPerson (p0 |> migrate_GameObjectTypes_PersonData)

        Evergreen.V4.GameObjectTypes.PickUpRelic p0 p1 ->
            Evergreen.V6.GameObjectTypes.PickUpRelic (p0 |> migrate_GameObjectIds_RelicId)
                (p1 |> migrate_GameObjectIds_PersonId)

        Evergreen.V4.GameObjectTypes.DropRelic p0 p1 ->
            Evergreen.V6.GameObjectTypes.DropRelic (p0 |> migrate_GameObjectIds_RelicId)
                (p1 |> migrate_GameObjectIds_PersonId)

        Evergreen.V4.GameObjectTypes.ActivateGenerosityTrap p0 p1 p2 ->
            Evergreen.V6.GameObjectTypes.ActivateGenerosityTrap (p0 |> migrate_GameObjectIds_PersonId)
                (p1 |> migrate_GameObjectIds_RelicId)
                p2

        Evergreen.V4.GameObjectTypes.BatchAction p0 ->
            Evergreen.V6.GameObjectTypes.BatchAction (p0 |> List.map migrate_GameObjectTypes_ActionOnGamestate)

        Evergreen.V4.GameObjectTypes.GameStateNoOp ->
            Evergreen.V6.GameObjectTypes.GameStateNoOp


migrate_GameObjectTypes_Direction : Evergreen.V4.GameObjectTypes.Direction -> Evergreen.V6.GameObjectTypes.Direction
migrate_GameObjectTypes_Direction old =
    case old of
        Evergreen.V4.GameObjectTypes.Up ->
            Evergreen.V6.GameObjectTypes.Up

        Evergreen.V4.GameObjectTypes.Down ->
            Evergreen.V6.GameObjectTypes.Down

        Evergreen.V4.GameObjectTypes.Left ->
            Evergreen.V6.GameObjectTypes.Left

        Evergreen.V4.GameObjectTypes.Right ->
            Evergreen.V6.GameObjectTypes.Right

        Evergreen.V4.GameObjectTypes.UpLeft ->
            Evergreen.V6.GameObjectTypes.UpLeft

        Evergreen.V4.GameObjectTypes.UpRight ->
            Evergreen.V6.GameObjectTypes.UpRight

        Evergreen.V4.GameObjectTypes.DownLeft ->
            Evergreen.V6.GameObjectTypes.DownLeft

        Evergreen.V4.GameObjectTypes.DownRight ->
            Evergreen.V6.GameObjectTypes.DownRight


migrate_GameObjectTypes_DirtData : Evergreen.V4.GameObjectTypes.DirtData -> Evergreen.V6.GameObjectTypes.DirtData
migrate_GameObjectTypes_DirtData old =
    { id = old.id |> migrate_GameObjectIds_DirtId
    , amount = old.amount
    , position = old.position |> migrate_GameObjectTypes_Point
    }


migrate_GameObjectTypes_PersonData : Evergreen.V4.GameObjectTypes.PersonData -> Evergreen.V6.GameObjectTypes.PersonData
migrate_GameObjectTypes_PersonData old =
    { id = old.id |> migrate_GameObjectIds_PersonId
    , name = old.name
    , experience = old.experience
    , position = old.position |> migrate_GameObjectTypes_Point
    , stats = old.stats |> migrate_GameObjectTypes_PersonStats
    , bestHighFiveBoost = Nothing
    }


migrate_GameObjectTypes_PersonStats : Evergreen.V4.GameObjectTypes.PersonStats -> Evergreen.V6.GameObjectTypes.PersonStats
migrate_GameObjectTypes_PersonStats old =
    old


migrate_GameObjectTypes_Point : Evergreen.V4.GameObjectTypes.Point -> Evergreen.V6.GameObjectTypes.Point
migrate_GameObjectTypes_Point old =
    old


migrate_GameObjectTypes_RelicData : Evergreen.V4.GameObjectTypes.RelicData -> Evergreen.V6.GameObjectTypes.RelicData
migrate_GameObjectTypes_RelicData old =
    { id = old.id |> migrate_GameObjectIds_RelicId
    , relicType = old.relicType |> migrate_GameObjectTypes_RelicType
    , rarity = old.rarity |> migrate_GameObjectTypes_RelicRarity
    , exp = old.exp
    }


migrate_GameObjectTypes_RelicPosition : Evergreen.V4.GameObjectTypes.RelicPosition -> Evergreen.V6.GameObjectTypes.RelicPosition
migrate_GameObjectTypes_RelicPosition old =
    case old of
        Evergreen.V4.GameObjectTypes.HeldBy p0 ->
            Evergreen.V6.GameObjectTypes.HeldBy (p0 |> migrate_GameObjectIds_PersonId)

        Evergreen.V4.GameObjectTypes.OnFloor p0 ->
            Evergreen.V6.GameObjectTypes.OnFloor (p0 |> migrate_GameObjectTypes_Point)


migrate_GameObjectTypes_RelicRarity : Evergreen.V4.GameObjectTypes.RelicRarity -> Evergreen.V6.GameObjectTypes.RelicRarity
migrate_GameObjectTypes_RelicRarity old =
    case old of
        Evergreen.V4.GameObjectTypes.Common ->
            Evergreen.V6.GameObjectTypes.Common

        Evergreen.V4.GameObjectTypes.Uncommon ->
            Evergreen.V6.GameObjectTypes.Uncommon

        Evergreen.V4.GameObjectTypes.Rare ->
            Evergreen.V6.GameObjectTypes.Rare

        Evergreen.V4.GameObjectTypes.Epic ->
            Evergreen.V6.GameObjectTypes.Epic

        Evergreen.V4.GameObjectTypes.Legendary ->
            Evergreen.V6.GameObjectTypes.Legendary


migrate_GameObjectTypes_RelicType : Evergreen.V4.GameObjectTypes.RelicType -> Evergreen.V6.GameObjectTypes.RelicType
migrate_GameObjectTypes_RelicType old =
    case old of
        Evergreen.V4.GameObjectTypes.CleanFast ->
            Evergreen.V6.GameObjectTypes.CleanFast

        Evergreen.V4.GameObjectTypes.MoreXP ->
            Evergreen.V6.GameObjectTypes.MoreXP

        Evergreen.V4.GameObjectTypes.DropAndDouble p0 ->
            Evergreen.V6.GameObjectTypes.DropAndDouble (p0 |> List.map migrate_GameObjectIds_PersonId)

        Evergreen.V4.GameObjectTypes.SplashBucket ->
            Evergreen.V6.GameObjectTypes.SplashBucket

        Evergreen.V4.GameObjectTypes.GuestBook p0 ->
            Evergreen.V6.GameObjectTypes.GuestBook (p0 |> SeqSet.map migrate_GameObjectIds_PersonId)

        Evergreen.V4.GameObjectTypes.DiminishingPower p0 ->
            Evergreen.V6.GameObjectTypes.DiminishingPower p0


migrate_Types_ActionPerformer : Evergreen.V4.Types.ActionPerformer -> Evergreen.V6.Types.ActionPerformer
migrate_Types_ActionPerformer old =
    case old of
        Evergreen.V4.Types.Client p0 ->
            Evergreen.V6.Types.Client (p0 |> migrate_GameObjectIds_PersonId)

        Evergreen.V4.Types.Server ->
            Evergreen.V6.Types.Server


migrate_Types_BackendToFrontendState : Evergreen.V4.Types.BackendToFrontendState -> Evergreen.V6.Types.BackendToFrontendState
migrate_Types_BackendToFrontendState old =
    { gameState = old.gameState |> migrate_Types_GameState
    , myId = old.myId |> migrate_GameObjectIds_PersonId
    , debugDirtParams = { minX = 0, maxX = 0, minY = 0, maxY = 0 }
    }


migrate_Types_DirtByLocation : Evergreen.V4.Types.DirtByLocation -> Evergreen.V6.Types.DirtByLocation
migrate_Types_DirtByLocation old =
    old |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_GameObjectTypes_Point migrate_GameObjectTypes_DirtData) |> SeqDict.fromList


migrate_Types_FrontendMsg : Evergreen.V4.Types.FrontendMsg -> Evergreen.V6.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V4.Types.UrlClicked p0 ->
            Evergreen.V6.Types.UrlClicked p0

        Evergreen.V4.Types.UrlChanged p0 ->
            Evergreen.V6.Types.UrlChanged p0

        Evergreen.V4.Types.PerformAction p0 ->
            Evergreen.V6.Types.PerformAction (p0 |> migrate_GameObjectTypes_ActionOnGamestate)

        Evergreen.V4.Types.ClickedPleaseMakeMeDirty ->
            Evergreen.V6.Types.ClickedPleaseMakeMeDirty

        Evergreen.V4.Types.DebugGenerateRelic ->
            Evergreen.V6.Types.DebugGenerateRelic

        Evergreen.V4.Types.ActivatedRelic p0 p1 ->
            Evergreen.V6.Types.ActivatedRelic (p0 |> migrate_GameObjectIds_PersonId)
                (p1 |> migrate_GameObjectIds_RelicId)

        Evergreen.V4.Types.ClickTarget p0 ->
            Evergreen.V6.Types.ClickTarget (p0 |> migrate_GameObjectTypes_Point)

        Evergreen.V4.Types.Tick p0 ->
            Evergreen.V6.Types.Tick p0

        Evergreen.V4.Types.ToggleDebugStuff ->
            Evergreen.V6.Types.ToggleDebugStuff

        Evergreen.V4.Types.CloseModals ->
            Evergreen.V6.Types.CloseModals

        Evergreen.V4.Types.ReceivedMapSize p0 ->
            Evergreen.V6.Types.ReceivedMapSize p0

        Evergreen.V4.Types.ToggleMobileRelicMenu ->
            Evergreen.V6.Types.ToggleMobileRelicMenu

        Evergreen.V4.Types.NoOpFrontendMsg ->
            Evergreen.V6.Types.NoOpFrontendMsg

        Evergreen.V4.Types.NukeBackend ->
            Evergreen.V6.Types.NukeBackend


migrate_Types_FrontendPlayingState : Evergreen.V4.Types.FrontendPlayingState -> Evergreen.V6.Types.FrontendPlayingState
migrate_Types_FrontendPlayingState old =
    { backendConfirmedGameState = old.backendConfirmedGameState |> migrate_Types_GameState
    , optimisticActions = old.optimisticActions |> List.map migrate_GameObjectTypes_ActionOnGamestate
    , myId = old.myId |> migrate_GameObjectIds_PersonId
    , targetPosition = old.targetPosition
    , showingDebugStuff = old.showingDebugStuff
    , mapSize = old.mapSize
    , cameraPosition = old.cameraPosition |> migrate_GameObjectTypes_Point
    , mobileRelicMenuOpen = old.mobileRelicMenuOpen
    , debugDirtParams = { minX = 0, maxX = 0, minY = 0, maxY = 0 }
    , currentTime = Effect.Time.millisToPosix 0
    , stunnedUntil = Effect.Time.millisToPosix 0
    , cleaningRandom = 0
    }


migrate_Types_FrontendState : Evergreen.V4.Types.FrontendState -> Evergreen.V6.Types.FrontendState
migrate_Types_FrontendState old =
    case old of
        Evergreen.V4.Types.Loading ->
            Evergreen.V6.Types.Loading

        Evergreen.V4.Types.Playing p0 ->
            Evergreen.V6.Types.Playing (p0 |> migrate_Types_FrontendPlayingState)

        Evergreen.V4.Types.Error p0 ->
            Evergreen.V6.Types.Error p0


migrate_Types_GameState : Evergreen.V4.Types.GameState -> Evergreen.V6.Types.GameState
migrate_Types_GameState old =
    { personDict = old.personDict |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_GameObjectIds_PersonId migrate_GameObjectTypes_PersonData) |> SeqDict.fromList
    , relicsByLocation = old.relicsByLocation |> migrate_Types_RelicsByLocation
    , dirtByLocation = old.dirtByLocation |> migrate_Types_DirtByLocation

    -- generate the index from the relicsByLocation
    , relicIdToLocationIndex =
        old.relicsByLocation
            |> migrate_Types_RelicsByLocation
            |> Evergreen.V6.GameState.calculateRelicIdToLocationIndex
    }


migrate_Types_RelicsById : Evergreen.V4.Types.RelicsById -> Evergreen.V6.Types.RelicsById
migrate_Types_RelicsById old =
    old |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_GameObjectIds_RelicId migrate_GameObjectTypes_RelicData) |> SeqDict.fromList


migrate_Types_RelicsByLocation : Evergreen.V4.Types.RelicsByLocation -> Evergreen.V6.Types.RelicsByLocation
migrate_Types_RelicsByLocation old =
    old |> SeqDict.toList |> List.map (Tuple.mapBoth migrate_GameObjectTypes_RelicPosition migrate_Types_RelicsById) |> SeqDict.fromList


migrate_Types_ToBackend : Evergreen.V4.Types.ToBackend -> Evergreen.V6.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V4.Types.NoOpToBackend ->
            Evergreen.V6.Types.NoOpToBackend

        Evergreen.V4.Types.ClientPerformsAction p0 ->
            Evergreen.V6.Types.ClientPerformsAction (p0 |> migrate_GameObjectTypes_ActionOnGamestate)

        Evergreen.V4.Types.PleaseMakeMeDirty ->
            Evergreen.V6.Types.PleaseMakeMeDirty

        Evergreen.V4.Types.PleaseGenerateRelic ->
            Evergreen.V6.Types.PleaseGenerateRelic

        Evergreen.V4.Types.PleaseActivateRelic p0 p1 ->
            Evergreen.V6.Types.PleaseActivateRelic (p0 |> migrate_GameObjectIds_PersonId)
                (p1 |> migrate_GameObjectIds_RelicId)

        Evergreen.V4.Types.PleaseNukeBackend ->
            Evergreen.V6.Types.PleaseNukeBackend


migrate_Types_ToFrontend : Evergreen.V4.Types.ToFrontend -> Evergreen.V6.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V4.Types.NoOpToFrontend ->
            Evergreen.V6.Types.NoOpToFrontend

        Evergreen.V4.Types.OtherClientPerformedAction p0 p1 ->
            Evergreen.V6.Types.OtherClientPerformedAction (p0 |> migrate_Types_ActionPerformer)
                (p1 |> migrate_GameObjectTypes_ActionOnGamestate)

        Evergreen.V4.Types.UpdateFullState p0 ->
            Evergreen.V6.Types.UpdateFullState (p0 |> migrate_Types_BackendToFrontendState)
